### ISSUE TITLE
Testing Tab

### ISSUE THREAD

**Issue by marstamm** [camunda/rpa-runtime#12]
Create a reusable component for testing RPA scripts. This uses deploy and run. 

- [x] Selection and configuration of runtime
  - [x] Installation hint
  - [x] Port configuration (local development)
- [x] Run dialog
  - [x] Runner selection
  - [x] Variables
- [x] Bottom Panel
  - [x] Empty state
  - [x] Loading state
  - [x] Finished state (pass/fail)

**Comment by natanielstrack** [comment]
Hey @marstamm,
I notice that his tasks was flagged as 8.8 but on our roadmap it was planned for the 8.7 (1/2 and 2/2).
Did something changed in the plans?

**Comment by marstamm** [comment]
When creating the tasks, I added all tasks that are needed for RPA 1.0 to the 8.8 milestone. We do not have a 8.7 milestone in this repo (yet)

**Comment by marstamm** [comment]
(The idea when I created the milestone was to track overall progress through it, but we went with the epic tasklist as it works better with issues through multiple projects. We can adjust to reflect and add an 8.7 milestone as well)

**Comment by natanielstrack** [comment]
> (The idea when I created the milestone was to track overall progress through it, but we went with the epic tasklist as it works better with issues through multiple projects. We can adjust to reflect and add an 8.7 milestone as well)

Got it, clear now.
In this case, I suggest we create the 8.7 milestone. 🙂

**Comment by marstamm** [comment]
Agreed. I'll take care of it
