### ISSUE TITLE
Onboard Kostiantyn

### ISSUE THREAD

**Issue by marstamm** [camunda/rpa-runtime#13]
> __Notice:__ This document is work in progress, help us to improve it.

# Onboarding

This document describes [prerequisites](#prerequisites), the [process we follow](#schedule), [additional topics](#potential-topics) and [strategies](#onboarding-strategies) relevant to the onboarding of new team members.

> \[!TIP]
> To create a new onboarding issue, copy the remainders of this file and replace individual parts:
>
> * `https://COMPANY_ONBOARDING_CHECKLIST_URL` - Link to company onboarding list
> * `@BUDDY` - GitHub handle of onboarding buddy

---

> \[!IMPORTANT]
> We want you to be a [manager of one](https://confluence.camunda.com/display/HAN/Manager+of+One). Own your onboarding, reach out proactively to your buddy or the team.
>
> [__@marstamm__](https://github.com/marstamm) is your [onboarding buddy](https://about.gitlab.com/handbook/people-operations/directly-responsible-individuals/). They guide you, connect you to others, delegate to team members for carrying out individual onboarding activities and ensure you get all the help you need.

> \[!IMPORTANT]
> We want your onboarding to be successful, and effective. To support this we ask you to give team-related onboarding activities priority over [company onboarding activities](https://COMPANY_ONBOARDING_CHECKLIST_URL).
>
> Rest assured, you'll get to know everything that you need to know sooner or later.

### Initial Setup

Manager and onboarding buddy ensure that the following is accounted for:

* [x] Buddy assigned ([__@BUDDY__](https://github.com/BUDDY))
* [ ] Connected to [company onboarding checklist](https://COMPANY_ONBOARDING_CHECKLIST_URL)
* [ ] Added to <rpa-team@camunda.com> distribution list (via IT)
* [x] Added to relevant slack channels [`#rpa-team`](https://camunda.slack.com/archives/GP70M0J6M), [`#prj-rpa`]
* [x] Invited to team ceremonies (regular invites)
  * [x] Weekly
* [x] Onboarding issue exists based on this document
  * [x] Assigned to new colleague
* [ ] Scheduled sync with Manager

## Schedule

> \[!NOTE]
>
> We created this onboarding plan to guide you through your first weeks. Work your way through it in your own pace, keep it updated and adjust it where you see fit after consulting with your onboarding budy.

### First Day

The goal of your first day is to meet the team, get ready for development _and_ work on / complete your first task:

* [x] Set up means of communication (Outlook, Slack, GitHub) and ensure accounts are working
* [x] get to know the team
* [x] Get to know our product
* [x] set up a basic dev environment
* [x] learn how we [work on issues](https://github.com/bpmn-io/internal-docs/tree/master/development#working-on-an-issue)
* [x] learn about our [definition of done](https://github.com/bpmn-io/internal-docs/tree/master/development/DEFINITION_OF_DONE.md)

---

See also [company onboarding checklist](https://COMPANY_ONBOARDING_CHECKLIST_URL).

**Comment by marstamm** [comment]
Had a fist chat with @kzraitel

Discussion topics:
 - Welcome to the team and team ceremonies
 - Quick introduction to Camunda and the Workflow engine
 - Deep dive into RPA and the planned architecture

Follow Ups:
  - Ensure all services are available for onboarding, especially
    - Camunda Academy for C8 onboarding course
    - C8-SaaS for development setup and getting to know Camunda

**Comment by natanielstrack** [comment]
The organization bellow was created for the RPA team. @marstamm and @kzraitel were add.
It is currently in a Trial plan, a request to change it to an Internal plan was send to the Console Team.

**Comment by marstamm** [comment]
@natanielstrack : We need to organize Okta access to `C8-Saas-Dev` as well, so that @kzraitel can access the newly created org.

Reason: Identity enforces SSO login for `@camunda` emails, but he has no access to the app
