### ISSUE TITLE
W45 - 2024

### ISSUE THREAD

**Issue by natanielstrack** [camunda/rpa-runtime#7]
This weeks moderator is ... and summary writer is ...

### Agenda

- [x] Last week in five minutes (progress, demo, impediments, learnings)
  - [x] Include review of [our taskboard](https://github.com/orgs/camunda/projects/136/views/1?filterQuery=assignee%3A%40me) (is your work reflected correctly?)
- [x] Review [product-hub](https://github.com/orgs/camunda/projects/9/views/92)
- [x] Review [retro action items](https://github.com/camunda/rpa-runtime/issues?q=is%3Aissue+is%3Aopen+label%3Aretrospective)
- [ ] Team member availability: [Upcoming Holidays anyone?](https://app.hibob.com/time-off/peoples-time-off/calendar)

### Last week in 5 Minutes
Everyone adds a summary of their weeks work here.

##### Last week
* Finalizing planning and creating timeline for 8.8
* Breaking down epics into tasks
* Started on https://github.com/camunda/rpa-runtime/issues/9

##### Next
* Continue on https://github.com/camunda/rpa-runtime/issues/9
  * suggest and auto-import Keywords with missing libraries
  * Break into reusable component

##### Last week
* Fill in the BE position (external and current recruitment process)

##### Next
* Review roadmap with Martin to adjust to the new team members availability
* Get Zeebe support on BE onboarding

### Additional Topics
Everyone can add topics to this section.

*

**Comment by marstamm** [comment]
### Additional Topics

* RPAFramework maintenance
  * RPAFramework might not get support in the future
  * We need to figure out a mid-long term strategy. @marstamm to set up discussion

* @kzraitel Onboarding update
  * Needs access to Development tools as described in https://github.com/camunda/rpa-runtime/issues/13#issuecomment-2451905774
    * Camunda Accademy
    * Miro
    * A C8-SaaS environment
  * Onboarding Buddy for the Zeebe project
  * @natanielstrack to organize resources

**Comment by marstamm** [comment]
Next weekly issue: https://github.com/camunda/rpa-runtime/issues/14

**Comment by natanielstrack** [comment]
Resources were requested:
- https://github.com/camunda/rpa-runtime/issues/13#issuecomment-2455309845
- https://github.com/camunda/rpa-runtime/issues/13#issuecomment-2455312715
